name: Update CVE Database

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-cve-database:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run CVE updater
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        INITIAL_RUN: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
      run: |
        python cve-database-updater-github.py

    - name: Commit and push changes
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update CVE database - $(date -u +%Y-%m-%d)"
          git push origin main
        fi
